apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webserver
  labels:
      name: webserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: webserver
    spec:
      containers:
      - name: webserver
        image: "kennethreitz/httpbin"
        ports:
        - name: webserver-80
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  type: NodePort
  ports:
  - name: webserver-80
    port: 80
  selector:
    name: webserver
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webserver-ingress
  annotations:
   ingress.citrix.com/insecure-termination: "allow"
   kubernetes.io/ingress.class: "webserver-ingress"
   ingress.citrix.com/analyticsprofile: '{"webinsight": {"httpurl":"ENABLED", "httpuseragent":"ENABLED", "httphost":"ENABLED", "httpmethod":"ENABLED", "httpcontenttype":"ENABLED"}, "tcpinsight": {"tcpBurstReporting":"DISABLED"}}'
spec:
      tls:
       - secretName: 
      rules:
       - http:
          paths:
          - path: /
            backend:
              serviceName: webserver
              servicePort: 80
