apiVersion: v1
kind: ConfigMap
metadata:
  name: cic-configmap
  namespace: default
data:
   LOGLEVEL: 'debug'
   NS_PROTOCOL: 'http'
   NS_PORT: '80'
   NS_HTTP2_SERVER_SIDE: 'ON'
   NS_ANALYTICS_CONFIG: |
     distributed_tracing:
       enable: 'true'
       samplingrate: 100
     endpoint:
       server: 'X.X.X.X'
     timeseries:
       port: 5563
       metrics:
         enable: 'true'
         mode: 'avro'
       auditlogs:
         enable: 'true'
       events:
         enable: 'true'
     transactions:
       enable: 'true'
       port: 5557
